/**
 * SchemaMarkup Component
 * Injects JSON-LD structured data into page <head>
 * Used alongside generateOrganizationSchema, generateMedicalConditionSchema, etc.
 *
 * Props:
 *   - data: Schema object (already generated by schema.ts functions)
 *   - includeOrganization: Include KSA org schema (default: true)
 */

import React, { useEffect } from "react";
import { generateOrganizationSchema } from "@/lib/schema";

const SchemaMarkup = ({
  data,
  includeOrganization = true,
}) => {
  useEffect(() => {
    if (!data) return;

    // Prepare schemas
    const schemas = [];

    // Always include organization schema for authority
    if (includeOrganization) {
      schemas.push(generateOrganizationSchema());
    }

    // Include provided schema
    if (data) {
      schemas.push(data);
    }

    // Determine if we need @graph for multiple schemas
    let schemaContent;
    if (schemas.length > 1) {
      schemaContent = {
        "@context": "https://schema.org",
        "@graph": schemas,
      };
    } else {
      schemaContent = schemas[0];
    }

    // Create and inject script tag
    const script = document.createElement("script");
    script.type = "application/ld+json";
    script.textContent = JSON.stringify(schemaContent);
    script.id = "schema-markup";

    // Remove existing schema markup to avoid duplicates
    const existing = document.getElementById("schema-markup");
    if (existing) {
      existing.remove();
    }

    document.head.appendChild(script);

    return () => {
      // Cleanup on unmount
      const script = document.getElementById("schema-markup");
      if (script) {
        script.remove();
      }
    };
  }, [data, includeOrganization]);

  // Component doesn't render visible content
  return null;
};

export default SchemaMarkup;
